# Generated by Django 4.2.5 on 2023-10-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('roll_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_hero', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_card_number', models.CharField(max_length=10)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_details', models.TextField()),
                ('first_time_investment_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_card_number', models.CharField(max_length=20)),
                ('farmer_name1', models.CharField(max_length=100)),
                ('mobile_number1', models.CharField(max_length=15)),
                ('land1', models.CharField(max_length=10)),
                ('another_farmer_name', models.CharField(max_length=100)),
                ('mobile_number2', models.CharField(max_length=15)),
                ('land_area2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uplace', models.CharField(max_length=100)),
                ('ublock', models.CharField(max_length=100)),
                ('udate', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_weight', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserInformation', to='farmer.customuser')),
            ],
        ),
    ]
